#!/usr/bin/env node
/**
 * One-shot Supabase setup for Apartment Book.
 *
 * Preferred: a personal access token (https://supabase.com/dashboard/account/tokens)
 *   SUPABASE_ACCESS_TOKEN=sbp_xxx SUPABASE_PROJECT_REF=abcdefghij node scripts/supabase-setup.mjs
 * It will: run the migration + seed, fetch the API keys, write apps/web/.env.local,
 * and set the auth Site URL / redirect URLs.
 *
 * Alternative (database password only):
 *   SUPABASE_DB_URL="postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:5432/postgres" \
 *   node scripts/supabase-setup.mjs
 * It will run the migration + seed. You then fill in apps/web/.env.local yourself.
 *
 * Options: SITE_URL (default http://localhost:3000), SKIP_SEED=1, SKIP_MIGRATION=1,
 *          SKIP_ENV=1 (do not rewrite apps/web/.env.local; use when pointing auth at production)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const migrationsDir = path.join(root, "supabase/migrations");
const migrations = fs
  .readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .map((name) => ({ name, sql: fs.readFileSync(path.join(migrationsDir, name), "utf8") }));
const seedSql = fs.readFileSync(path.join(root, "supabase/seed.sql"), "utf8");
const envPath = path.join(root, "apps/web/.env.local");

const token = process.env.SUPABASE_ACCESS_TOKEN;
const dbUrl = process.env.SUPABASE_DB_URL;
const siteUrl = (process.env.SITE_URL || "http://localhost:3000").replace(/\/$/, "");
const API = "https://api.supabase.com";

function log(msg) { console.log(msg); }
function done(msg) { console.log(`  ✓ ${msg}`); }
function fail(msg) { console.error(`  ✗ ${msg}`); }

async function api(method, route, body) {
  const res = await fetch(`${API}${route}`, {
    method,
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  let data;
  try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) {
    const message = typeof data === "object" && data ? (data.message || data.error || JSON.stringify(data)) : String(data);
    throw new Error(`${method} ${route} → ${res.status}: ${message}`);
  }
  return data;
}

const firstRow = (rows) => (Array.isArray(rows) ? rows[0] : rows?.rows?.[0]);

/** Names of migrations already applied, tracked in public._migrations (created here). */
async function appliedMigrations(runQuery) {
  await runQuery("create table if not exists public._migrations (name text primary key, applied_at timestamptz not null default now()); alter table public._migrations enable row level security;");
  const rows = await runQuery("select name from public._migrations order by name");
  const list = (Array.isArray(rows) ? rows : rows?.rows ?? []).map((r) => r.name);
  if (list.length === 0) {
    // Projects set up before migration tracking existed: the first migration is
    // applied when the core tables are present.
    const probe = firstRow(await runQuery("select count(*)::int as n from pg_tables where schemaname = 'public' and tablename in ('apartments','messages','profiles')"));
    if (Number(probe?.n) === 3 && migrations[0]) {
      await runQuery(`insert into public._migrations (name) values ('${migrations[0].name}') on conflict do nothing`);
      list.push(migrations[0].name);
    }
  }
  return new Set(list);
}

async function applySql(runQuery) {
  if (process.env.SKIP_MIGRATION !== "1") {
    const applied = await appliedMigrations(runQuery);
    for (const m of migrations) {
      if (applied.has(m.name)) {
        done(`${m.name}: already applied`);
        continue;
      }
      await runQuery(m.sql);
      await runQuery(`insert into public._migrations (name) values ('${m.name}') on conflict do nothing`);
      done(`${m.name}: applied`);
    }
  }
  if (process.env.SKIP_SEED !== "1") {
    await runQuery(seedSql);
    const n = firstRow(await runQuery("select count(*)::int as n from public.universities"))?.n;
    const domains = (await runQuery("select email_domain from public.universities where email_domain is not null order by 1"));
    const list = (Array.isArray(domains) ? domains : domains?.rows ?? []).map((r) => r.email_domain);
    done(`seed applied: ${n} universities; sign-ups allowed from ${list.map((d) => "@" + d).join(", ") || "any domain"}`);
  }
}

function writeEnv(values) {
  const lines = [
    "# Generated by scripts/supabase-setup.mjs. Do not commit this file.",
    `NEXT_PUBLIC_SUPABASE_URL=${values.url}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${values.anonKey}`,
    `NEXT_PUBLIC_SITE_URL=${values.siteUrl}`,
    "",
  ];
  fs.writeFileSync(envPath, lines.join("\n"));
  done(`wrote ${path.relative(root, envPath)}`);
}

async function withManagementApi() {
  let ref = process.env.SUPABASE_PROJECT_REF;
  const projects = await api("GET", "/v1/projects");
  if (!ref) {
    if (projects.length === 1) ref = projects[0].id;
    else throw new Error(`Set SUPABASE_PROJECT_REF. Your projects: ${projects.map((p) => `${p.name} (${p.id})`).join(", ")}`);
  }
  const project = projects.find((p) => p.id === ref);
  if (!project) throw new Error(`Project ${ref} not found in this account`);
  log(`Project: ${project.name} (${ref}) · region ${project.region} · status ${project.status}`);
  if (project.status !== "ACTIVE_HEALTHY") log("  ! project is not ACTIVE_HEALTHY yet; SQL may fail until it finishes provisioning");

  log("\nDatabase");
  const runQuery = async (query) => api("POST", `/v1/projects/${ref}/database/query`, { query });
  await applySql(runQuery);

  log("\nAPI keys");
  const keys = await api("GET", `/v1/projects/${ref}/api-keys?reveal=true`);
  const anon = keys.find((k) => k.name === "anon") ?? keys.find((k) => k.type === "publishable") ?? keys.find((k) => /publishable/.test(k.name));
  if (!anon?.api_key) throw new Error(`Could not find the anon/publishable key. Keys: ${keys.map((k) => k.name).join(", ")}`);
  const url = `https://${ref}.supabase.co`;
  if (process.env.SKIP_ENV === "1") done("kept existing apps/web/.env.local (SKIP_ENV=1)");
  else writeEnv({ url, anonKey: anon.api_key, siteUrl });

  log("\nAuth settings");
  const current = await api("GET", `/v1/projects/${ref}/config/auth`);
  const existing = (current.uri_allow_list || "").split(",").map((s) => s.trim()).filter(Boolean);
  const wanted = new Set([...existing, "http://localhost:3000/auth/callback", `${siteUrl}/auth/callback`]);
  await api("PATCH", `/v1/projects/${ref}/config/auth`, {
    site_url: siteUrl,
    uri_allow_list: [...wanted].join(","),
  });
  done(`site_url = ${siteUrl}`);
  done(`redirect URLs = ${[...wanted].join(", ")}`);
  log(`  email confirmation: ${current.mailer_autoconfirm ? "OFF (sign-ups log in immediately)" : "ON (users must click the email link)"}`);
  log(`  google sign-in: ${current.external_google_enabled ? "enabled" : "not enabled (optional)"}`);

  log("\nAll done. Next: npm run dev");
}

async function withDatabaseUrl() {
  const { default: pg } = await import("pg");
  const client = new pg.Client({ connectionString: dbUrl, ssl: { rejectUnauthorized: false } });
  await client.connect();
  log("Connected to the database");
  try {
    const runQuery = async (query) => (await client.query(query)).rows;
    await applySql(runQuery);
  } finally {
    await client.end();
  }
  if (!fs.existsSync(envPath)) {
    log(`\nNow copy apps/web/.env.example to apps/web/.env.local and fill in the project URL and anon key.`);
  }
  log("\nAll done.");
}

try {
  if (token) await withManagementApi();
  else if (dbUrl) await withDatabaseUrl();
  else {
    fail("Set SUPABASE_ACCESS_TOKEN (+ SUPABASE_PROJECT_REF) or SUPABASE_DB_URL. See the comment at the top of this file.");
    process.exit(1);
  }
} catch (error) {
  fail(error.message);
  process.exit(1);
}
