import fs from "node:fs";
import { createClient } from "@supabase/supabase-js";
const ref = "dskbzoqreandwwpxiplh";
const keys = await (await fetch(`https://api.supabase.com/v1/projects/${ref}/api-keys?reveal=true`, { headers: { Authorization: `Bearer ${process.env.SUPABASE_ACCESS_TOKEN}` } })).json();
const admin = createClient(`https://${ref}.supabase.co`, keys.find((k) => k.name === "service_role").api_key, { auth: { persistSession: false, autoRefreshToken: false } });
const s = JSON.parse(fs.readFileSync(new URL(".sim-state.json", import.meta.url), "utf8"));
const { data: convs } = await admin.from("conversation_members").select("conversation_id").in("user_id", [s.me.id, s.other.id]);
for (const c of new Set((convs ?? []).map((c) => c.conversation_id))) await admin.from("conversations").delete().eq("id", c);
for (const id of [s.me.id, s.other.id]) await admin.auth.admin.deleteUser(id);
console.log("cleaned up sim users and their data");
